# Site Settings
locale            : "en-US"
title             : "Personal Site"
title_separator   : "-"
name              : "Nathan Kong"
description       : "Builder with Interest in Autonomous Systems and Hardware-Software Codesign"
url               : "https://github.io"
baseurl           : ""
repository        : "1nathankong/1nathankong.github.io"
teaser            : "/castle_in_sky.png"
breadcrumbs       : false
words_per_minute  : 160
future            : true
read_more         : "disabled"

# The theme setting
theme: jekyll-theme-minimal
