# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Personal Site"
title_separator          : "-"
name                     : &name Nathan Kong
description              : &description Builder with Interest in Autonomous Systems and Hardware-Software Codesign
url                      : "https://1nathankong.github.io"
baseurl                  : ""
repository               : "1nathankong/1nathankong.github.io"
teaser                   :  "castle_in_sky.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add